language: php

php:
  - 7.3

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate --seed

before_install:
  - mysql -e 'CREATE DATABASE jadebear;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false